# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Wade's Blog
baseurl: "" # the subpath of your site, e.g. /blog
image: https://i.imgur.com/7GZTAp0.jpg

# Social media
author:
  name: James Wade
  linkedin: jpswade
  twitter: jpswade
  github: jpswade

social:
  - name: twitter
    username: jpswade
    url: https://twitter.com/
  - name: github
    username: jpswade
    url: https://github.com/
  - name: linkedin
    username: jpswade
    url: https://uk.linkedin.com/in/

# Build settings
markdown: kramdown

# Imported from Wordpress
url: https://wade.be
name: James Wade's Blog
description: Research and Development
donate: Has this post been useful? <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=james@wade.be&item_name=Buy%20me%20a%20beer!&item_number=beer001&amount=5%2e00&currency_code=GBP">Buy me a coffee or beer!</a>

# Custom
paginate: 5
#paginate_path: "/page/:num/"
highlighter: rouge

# Publish posts or collection documents with a future date.
future: false

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"