# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Wade's Blog
baseurl: "" # the subpath of your site, e.g. /blog
image: http://i.imgur.com/7GZTAp0.jpg

# Social media
author:
  name: James Wade
  facebook: jpswade
  linkedin: jpswade
  twitter: jpswade
  github: jpswade

social:
  - name: facebook
    username: jpswade
    url: https://www.facebook.com/
  - name: linkedin
    username: jpswade
    url: https://uk.linkedin.com/in/
  - name: twitter
    username: jpswade
    url: https://twitter.com/
  - name: github
    username: jpswade
    url: https://github.com/

# Build settings
markdown: kramdown

# Imported from Wordpress
url: http://wade.be
name: James Wade's Blog
description: Research and Development

# Custom
paginate: 5
highlighter: rouge

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-paginate